extraction:
  cpp:
    after_prepare: 
      - python report.py 66
  cobol:
    after_prepare: 
      - python report.py 66
  csharp:
    after_prepare: 
      - python report.py 66
  java:
    after_prepare: 
      - python report.py 66
  javascript:
    after_prepare: 
      - python report.py 66
  python:
    after_prepare: 
      - python report.py 66
